name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: ${{ github.repository_owner }}

      - name: move generated svgs
        run: |
          mv output/light.svg assets/breakout-light.svg
          mv output/dark.svg assets/breakout-dark.svg

      - name: configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: commit and push svgs
        run: |
          git add assets/breakout-light.svg assets/breakout-dark.svg
          git commit -m "Update project" || echo "No changes to commit"
          git push